### ISSUE TITLE
Enforce consistent code formatting with Black & isort in CI and pre-commit

### ISSUE THREAD

**Issue by conorheins** [infer-actively/pymdp#183]
### 🐛 Motivation

We currently rely on `flake8 --exit-zero` in our GitHub Actions workflow, which only emits warnings for style issues (line-length, complexity, etc.). That means formatting can drift and lead to noisy “reformat on merge” commits. To keep the codebase consistently styled and catch formatting errors early, we should:

1. Fail CI if code isn’t Black-formatted or imports aren’t sorted by isort
2. Provide a `.pre-commit-config.yaml` so contributors get instant feedback locally

---

### 📦 Proposed Changes

1. **CI (GitHub Actions)**

   * Install `black` and `isort` alongside existing lint tools
   * Add steps before `flake8` to run:

     ```yaml
     - name: Check formatting with Black
       run: black --check . --line-length 127

     - name: Check import order with isort
       run: isort --check-only .
     ```
   * (Optionally bump Black’s default line length to match `flake8`’s `--max-line-length=127`.)

2. **Pre-commit Hooks**

   * Add a `.pre-commit-config.yaml` at repo root:

     ```yaml
     repos:
       - repo: https://github.com/psf/black
         rev: 23.9.1
         hooks:
           - id: black
             args: [--line-length=127]

       - repo: https://github.com/PyCQA/isort
         rev: 5.12.0
         hooks:
           - id: isort
             args: ["--profile=black"]

       - repo: https://github.com/pycqa/flake8
         rev: 6.0.0
         hooks:
           - id: flake8
             args: ["--max-line-length=127", "--max-complexity=10"]
     ```
   * Update the CONTRIBUTING guide to instruct:

     ```bash
     pip install pre-commit
     pre-commit install
     ```

---

### ✅ Acceptance Criteria

* [ ] CI fails when any Python file isn’t formatted by Black
* [ ] CI fails when imports aren’t sorted according to isort’s Black profile
* [ ] A working `.pre-commit-config.yaml` is added to the repo
* [ ] Documentation updated (CONTRIBUTING.md or README) with setup instructions

---

*This will help us keep the style consistent, cut down on formatting-only PR churn, and surface real lint/test failures more clearly.*
